name: CMake Build

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libc++-18-dev clang-18
    - name: Cache Build
      id: restore-cache-build
      uses: actions/cache/restore@v4
      with:
        path: build
        key: ${{ runner.os }}-build
    - name: CMake Action
      uses: threeal/cmake-action@v1.3.0
      with:
        args: -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS='-D__cpp_concepts=202002L' -DCMAKE_EXE_LINKER_FLAGS='-static'
        run-build: true
        c-compiler: clang-18
        cxx-compiler: clang++-18
    - uses: actions/cache/save@v3
      name: Save build cache
      with:
        path: build
        key: ${{ runner.os }}-build
    - name: Run tests
      working-directory: ./build
      run: ctest --rerun-failed --output-on-failure .
    - uses: actions/upload-artifact@v4
      with:
        name: 'ubuntu-cli'
        path: build/bin/ts-compiler
        if-no-files-found: error
        retention-days: 90
        compression-level: 6
        overwrite: true
